services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    ports:
      - "3010:8081"
    volumes:
      - /mnt/sec/media/music:/downloads
      - /mnt/sec/apps/metube:/config
    restart: unless-stopped

  postprocessor:
    image: ghcr.io/therepos/docker-metubetag:latest
    container_name: metubetag
    volumes:
      - /mnt/sec/media/music:/music
      - /mnt/sec/apps/metube:/metube
    restart: unless-stopped